In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['Unnamed: 32','id'], inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)
x_train

array([[ 1.24386264, -0.18328979,  1.14983671, ...,  0.66534825,
         0.54760788, -0.83859532],
       [ 0.59428738, -0.30910196,  0.57187399, ...,  0.11563972,
        -0.1533305 , -0.11524369],
       [-0.05824049, -0.02661803, -0.12895931, ..., -0.50529865,
        -0.89151683, -0.44430939],
       ...,
       [ 1.80190683,  1.77510726,  1.79629871, ...,  1.56501208,
         0.6576586 , -0.42711497],
       [ 2.70835958,  0.63805006,  2.58404048, ...,  1.86541618,
         1.19606054,  0.49486191],
       [-0.18815554,  2.10269367, -0.25054554, ..., -0.87213232,
        -0.31925312, -0.76566725]])

In [ ]:
y_train

186    M
141    M
481    B
369    M
461    M
      ..
286    B
393    M
366    M
164    M
377    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
y_test

323    M
385    M
236    M
3      M
389    M
      ..
233    M
25     M
557    B
274    M
463    B
Name: diagnosis, Length: 114, dtype: object

In [ ]:
encoder  = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_test

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0])

In [ ]:
len(y_test)

114

In [ ]:
import torch
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [ ]:
y_test_tensor

tensor([1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0.,
        1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0.,
        0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
        1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
        0., 1., 1., 0., 1., 0.])

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
import torch.nn as nn

In [ ]:
class Neuralnetwork(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out =self.linear(features)
    out = self.sigmoid(out)
    return out

  loss_function = nn.BCELoss()






In [ ]:
model = Neuralnetwork(x_train_tensor.shape[1])


In [ ]:
model.linear.weight

Parameter containing:
tensor([[-0.0140, -0.1459,  0.0868,  0.0257, -0.0156, -0.1157,  0.1080,  0.0578,
         -0.1487,  0.1276,  0.0149, -0.0154, -0.1518,  0.0196, -0.0474, -0.0265,
          0.1097,  0.1105, -0.0278, -0.1284,  0.1623, -0.1407, -0.1027,  0.0923,
          0.0837, -0.1263,  0.1051, -0.0731, -0.0723, -0.0549]],
       requires_grad=True)

In [ ]:
learning_rate = 0.1
epochs = 50

In [ ]:
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

In [ ]:
# create model

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(x_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor.view(-1,1))

# zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()
  optimizer.zero_grad()



  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()



  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.09155251085758209
Epoch: 2, Loss: 0.09138990193605423
Epoch: 3, Loss: 0.09122908115386963
Epoch: 4, Loss: 0.0910700112581253
Epoch: 5, Loss: 0.09091264009475708
Epoch: 6, Loss: 0.09075695276260376
Epoch: 7, Loss: 0.09060293436050415
Epoch: 8, Loss: 0.09045053273439407
Epoch: 9, Loss: 0.09029973298311234
Epoch: 10, Loss: 0.09015051275491714
Epoch: 11, Loss: 0.09000282734632492
Epoch: 12, Loss: 0.08985666930675507
Epoch: 13, Loss: 0.089711993932724
Epoch: 14, Loss: 0.08956878632307053
Epoch: 15, Loss: 0.08942706137895584
Epoch: 16, Loss: 0.08928673714399338
Epoch: 17, Loss: 0.08914780616760254
Epoch: 18, Loss: 0.08901025354862213
Epoch: 19, Loss: 0.08887406438589096
Epoch: 20, Loss: 0.08873920142650604
Epoch: 21, Loss: 0.08860565721988678
Epoch: 22, Loss: 0.08847339451313019
Epoch: 23, Loss: 0.08834241330623627
Epoch: 24, Loss: 0.08821266889572144
Epoch: 25, Loss: 0.08808417618274689
Epoch: 26, Loss: 0.08795688301324844
Epoch: 27, Loss: 0.0878307893872261
Epoch: 28, Los

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.8).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5461680293083191


new model using nn model

In [ ]:
import torch
import torch.nn as nn


In [ ]:
class MyNeuralNetwork(nn.M