In [ ]:
import torch

In [ ]:
b =torch.tensor([5.0], requires_grad=True)

In [ ]:
a = b**2

In [ ]:
c = torch.sin(a)

In [ ]:
c

tensor([-0.1324], grad_fn=<SinBackward0>)

In [ ]:
c.backward()

In [ ]:
c.grad

/tmp/ipython-input-2950652411.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  c.grad


In [ ]:
b.grad

tensor([9.9120])

In [ ]:
a.grad

/tmp/ipython-input-625247546.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  a.grad


In [ ]:
a.grad

In [ ]:
b

tensor([5.], requires_grad=True)

In [ ]:
a

tensor([25.], grad_fn=<PowBackward0>)

In [ ]:
b.grad

tensor([9.9120])

In [ ]:
c

tensor([-0.1324], grad_fn=<SinBackward0>)

In [ ]:
x = torch.tensor([2.0], requires_grad =True)

In [ ]:
w = torch.tensor([3.0],requires_grad = True)
y = (5*(x**2)+x)

In [ ]:
z = y*w

In [ ]:
z.backward()

In [ ]:
y

tensor([22.], grad_fn=<AddBackward0>)

In [ ]:
y.grad

/tmp/ipython-input-486760323.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more information. (Triggered internally at /pytorch/build/aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [ ]:
x

tensor([2.], requires_grad=True)

In [ ]:
x.grad

tensor([63.])

In [ ]:
y

tensor([22.], grad_fn=<AddBackward0>)

In [ ]:
w

tensor([3.], requires_grad=True)

In [ ]:
w.grad.item()

22.0